### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by Huangshier** [farellsujanto/flutter_serial_communication#11]
## Problem Description

I encountered issues with connecting to the serial port while using the flutter_serial_communication plugin.

## Plugin version

I'm using version 0.2.4 of the flutter_serial_communication plugin.

## The device being used.

The device I'm using is an Android 5.1.1 with an RK3288 processor, and the baud rate is set to 9600.

## Call Code

```dart
void _openCloseSerial() {
    if(!_isOpen){
      int baudRate = int.parse(_selectedBaud); // Your device's baud rate
      _spTest.getAvailableDevices().then((devices) async {
        for (DeviceInfo device in devices) {
          if (device.deviceName == _selectedCOM) {
            bool isConnectionSuccess = await _spTest.connect(device, baudRate);
            debugPrint('获取${device.deviceName},连接:$isConnectionSuccess\r\n');
            if(isConnectionSuccess){
              setState(() {
                _isOpen = isConnectionSuccess;
              });
            }
            else{
              debugPrint('打开串口失败\r\n');
            }
            break;
          }
        }
      });
    }
    else{
      _spTest.disconnect();
      setState(() {
        _isOpen = false;
      });
    }
}

```AndroidManifest.xml
    <uses-feature android:name="android.hardware.usb.host" />
    <uses-permission android:name="android.permission.USB_PERMISSION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

## Output Information

E/MethodChannel#flutter_serial_communication( 8896): Failed to handle method call
E/MethodChannel#flutter_serial_communication( 8896): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
E/MethodChannel#flutter_serial_communication( 8896): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.controlIn(Ch34xSerialDriver.java:123)
E/MethodChannel#flutter_serial_communication( 8896): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.getStatus(Ch34xSerialDriver.java:160)
E/MethodChannel#flutter_serial_communication( 8896): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.getControlLines(Ch34xSerialDriver.java:341)
E/MethodChannel#flutter_serial_communication( 8896): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.openPort(FlutterSerialCommunicationPlugin.java:245)
E/MethodChannel#flutter_serial_communication( 8896): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.connect(FlutterSerialCommunicationPlugin.java:238)
E/MethodChannel#flutter_serial_communication( 8896): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.onMethodCall(FlutterSerialCommunicationPlugin.java:100)
E/MethodChannel#flutter_serial_communication( 8896): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter_serial_communication( 8896): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter_serial_communication( 8896): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter_serial_communication( 8896): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/MethodChannel#flutter_serial_communication( 8896): 	at android.os.Handler.handleCallback(Handler.java:739)
E/MethodChannel#flutter_serial_communication( 8896): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/MethodChannel#flutter_serial_communication( 8896): 	at android.os.Looper.loop(Looper.java:135)
E/MethodChannel#flutter_serial_communication( 8896): 	at android.app.ActivityThread.main(ActivityThread.java:5280)
E/MethodChannel#flutter_serial_communication( 8896): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_serial_communication( 8896): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#flutter_serial_communication( 8896): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
E/MethodChannel#flutter_serial_communication( 8896): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
E/flutter ( 8896): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
E/flutter ( 8896): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.controlIn(Ch34xSerialDriver.java:123)
E/flutter ( 8896): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.getStatus(Ch34xSerialDriver.java:160)
E/flutter ( 8896): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.getControlLines(Ch34xSerialDriver.java:341)
E/flutter ( 8896): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.openPort(FlutterSerialCommunicationPlugin.java:245)
E/flutter ( 8896): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.connect(FlutterSerialCommunicationPlugin.java:238)
E/flutter ( 8896): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.onMethodCall(FlutterSerialCommunicationPlugin.java:100)
E/flutter ( 8896): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter ( 8896): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 8896): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter ( 8896): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
E/flutter ( 8896): 	at android.os.Handler.handleCallback(Handler.java:739)
E/flutter ( 8896): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter ( 8896): 	at android.os.Looper.loop(Looper.java:135)
E/flutter ( 8896): 	at android.app.ActivityThread.main(ActivityThread.java:5280)
E/flutter ( 8896): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8896): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter ( 8896): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
E/flutter ( 8896): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
E/flutter ( 8896): )
E/flutter ( 8896): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 8896): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 8896): <asynchronous suspension>
E/flutter ( 8896): #2      MethodChannelFlutterSerialCommunication.connect (package:flutter_serial_communication/flutter_serial_communication_method_channel.dart:51:9)
E/flutter ( 8896): <asynchronous suspension>
E/flutter ( 8896): #3      _MyHomePageState._openCloseSerial.<anonymous closure> (package:friot_serialport/main.dart:111:40)
E/flutter ( 8896): <asynchronous suspension>
E/flutter ( 8896): 

## Expected behavior

I expected the serial port to open successfully and run, but in reality, the error mentioned above occurred. In June, I was using version 0.2.3, and it was working fine at that time. However, when I retested recently, the problem persisted with both 0.2.3 and 0.2.4 versions.

**Comment by opensiam** [comment]
This error occurs in Android Native side ( FlutterSerialCommunicationPlugin.java )
Try to remove the command usbSerialPort.getControlLines() in the openPort() method.
I'm not sure this command is necessary for all UsbSerial drivers.

public void openPort() {
    try {
      usbSerialPort = driver.getPorts().get(0);
     **//  usbSerialPort.getControlLines();**
     ...
     ...

**Comment by nmiglio** [comment]
I had the same problem with a FTDI usb to serial converter.
The suggested fix solved my issue.

**Comment by farellsujanto** [comment]
Hi, sorry for the very late reply, I've updated the library to [v0.2.5](https://github.com/farellsujanto/flutter_serial_communication/releases/tag/v0.2.5) that has this fix. Please re-open the issue if its happening again.
