### ISSUE TITLE
Not getting whole bunch of data.

### ISSUE THREAD

**Issue by Alfaizkhan** [farellsujanto/flutter_serial_communication#2]
I'm also not getting the data in the application sometime.
I have to open application again, make a connection and then only it will work.
Any solution or tips?
Why it's happening.

`  Future<void> _deviceSerialMessageListener() async {
    flutterSerialCommunicationHome
        .getSerialMessageListener()
        .receiveBroadcastStream()
        .listen(
      (value) async {
       toast(value);
      },
    );
  }
`

**Comment by farellsujanto** [comment]
are you making a connection on the first time before re-opening the app?

**Comment by Alfaizkhan** [comment]
@farellsujanto 
No.
Already had one complete session of communication with the device.
But it stop working in between. then i have to close the app.
also without disconnecting device when I plug-out device, application crashing on disconnect() method.

**Comment by farellsujanto** [comment]
Let me check first on my end. Do you have device / flutter log? Serial device & android device info too if possible.

**Comment by Alfaizkhan** [comment]
@farellsujanto 


Failed to deliver inset state change to w=Window{ded63e4 u0 com.alfaizkhan.faremeter/com.alfaizkhan.faremeter.MainActivity EXITING}
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:4017)
	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4(InsetsStateController.java:351)
	at com.android.server.wm.InsetsStateController.$r8$lambda$An2IoiA3BeA5IWc6QwBOjKArM80(Unknown Source:0)
	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:106)
	at com.android.server.wm.WindowAnimator.$r8$lambda$fo2Nk5bb9hY3lvmHsTnTEwtZMbI(Unknown Source:0)
	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:44)
	
	
	
Device : Pixel 6 - Android 13
