### ISSUE TITLE
APP crash and force close when serial status connected and cable detached from device

### ISSUE THREAD

**Issue by ferryindra25** [farellsujanto/flutter_serial_communication#6]
E/AndroidRuntime(16611): FATAL EXCEPTION: SerialInputOutputManager
E/AndroidRuntime(16611): Process: id.farellsujanto.flutter_serial_communication_example, PID: 16611
E/AndroidRuntime(16611): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: SerialInputOutputManager
E/AndroidRuntime(16611):        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1433)
E/AndroidRuntime(16611):        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:1054)
E/AndroidRuntime(16611):        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:282)
E/AndroidRuntime(16611):        at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:452)
E/AndroidRuntime(16611):        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:212)
E/AndroidRuntime(16611):        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:251)
E/AndroidRuntime(16611):        at id.farellsujanto.flutter_serial_communication.DeviceConnectionHandler.success(DeviceConnectionHandler.java:12)
E/AndroidRuntime(16611):        at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.disconnect(FlutterSerialCommunicationPlugin.java:205)
E/AndroidRuntime(16611):        at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.onRunError(FlutterSerialCommunicationPlugin.java:224)
E/AndroidRuntime(16611):        at com.hoho.android.usbserial.util.SerialInputOutputManager.run(SerialInputOutputManager.java:209)
E/AndroidRuntime(16611):        at java.lang.Thread.run(Thread.java:1012)

**Comment by ferryindra25** [comment]
@farellsujanto

**Comment by ferryindra25** [comment]
thank you @DominikStarke
