### ISSUE TITLE
App crashes on connect()

### ISSUE THREAD

**Issue by krithik-ranjan** [farellsujanto/flutter_serial_communication#8]
Hi, 
I'm trying to test out my system with the given example, and every time I press the connect button (which calls `_flutterSerialCommunicationPlugin.connect(deviceInfo, 115200);`, the app crashes with the following error on the debug console:
```
D/AndroidRuntime( 2370): Shutting down VM
E/AndroidRuntime( 2370): FATAL EXCEPTION: main
E/AndroidRuntime( 2370): Process: com.example.serial_app, PID: 2370
E/AndroidRuntime( 2370): java.lang.RuntimeException: Error receiving broadcast Intent { act=id.farellsujanto.flutter_serial_communication.GRANT_USB flg=0x10 (has extras) } in id.farellsujanto.flutter_serial_communication.USBGrantReceiver@62fcb1d
E/AndroidRuntime( 2370): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1581)
E/AndroidRuntime( 2370): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime( 2370): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 2370): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2370): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime( 2370): 	at android.app.ActivityThread.main(ActivityThread.java:8068)
E/AndroidRuntime( 2370): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2370): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime( 2370): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/AndroidRuntime( 2370): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.hardware.usb.UsbDeviceConnection.controlTransfer(int, int, int, int, byte[], int, int)' on a null object reference
E/AndroidRuntime( 2370): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.controlIn(Ch34xSerialDriver.java:123)
E/AndroidRuntime( 2370): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.getStatus(Ch34xSerialDriver.java:160)
E/AndroidRuntime( 2370): 	at com.hoho.android.usbserial.driver.Ch34xSerialDriver$Ch340SerialPort.getControlLines(Ch34xSerialDriver.java:341)
E/AndroidRuntime( 2370): 	at id.farellsujanto.flutter_serial_communication.FlutterSerialCommunicationPlugin.openPort(FlutterSerialCommunicationPlugin.java:245)
E/AndroidRuntime( 2370): 	at id.farellsujanto.flutter_serial_communication.USBGrantReceiver.onReceive(USBGrantReceiver.java:21)
E/AndroidRuntime( 2370): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1566)
E/AndroidRuntime( 2370): 	... 8 more
I/Process ( 2370): Sending signal. PID: 2370 SIG: 9
Lost connection to device.
```

The previous call to getAvailableDevices() returns appropriately when I connect an Arduino to the phone. What could be the cause for this issue? Is there some additional setup I need other than adding the `flutter_serial_communication` package?

Thank you!

**Comment by waitwalker** [comment]
Hi,@krithik-ranjan I found FlutterSerialCommunicationPlugin->openPort->usbSerialPort.getControlLines() throw an exception, and I changed this to call the usbSerialPort. getSupportedControlLines() method, then it runs ok.

**Comment by ivan2angelov** [comment]
I have the same issue on Android 14. Isn't there gonna be an official fix?

**Comment by farellsujanto** [comment]
Hi, sorry for the very late reply, I've updated the library to [v0.2.5](https://github.com/farellsujanto/flutter_serial_communication/releases/tag/v0.2.5) that has this fix. Please re-open the issue if its happening again.

**Comment by ivan2angelov** [comment]
Unfortunately release v0.2.5 does not solve the issue.
I made Flutter app (it is very much the same as the example app in library code), build it and I get following error:
`Exception has occurred.
PlatformException (PlatformException(error, com.example.flutter_application_1: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.example.flutter_application_1: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`

here is the pubspec.yaml I have:
```
name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_serial_communication: ^0.2.5
  plugin_platform_interface: '>=2.0.0 <2.1.5'
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
```

When I build the app I made sure that flutter_serial_communication is indeed 0.2.5 -  I checked the dependency file ./app/intermediates/flutter/debug/flutter_build.d and it contains:
```
C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\LICENSE C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\flutter_serial_communication.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\flutter_serial_communication_method_channel.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\flutter_serial_communication_platform_interface.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\flutter_serial_communication-0.2.5\\lib\\models\\device_info.dart C:\\Users\\ian\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\leak_tracker-10.0.4\\LICENSE
```

What I find interesting is that if I build locally the library downloaded from GitHub it works, but if I use it via pubspec.yaml it fails.
